name: Run packer build on AWS

on:
	push:
    	branches:
        	- main


permissions:
	id-token: write
	contents: read
	pull-requests: write


env:
  terraformVersion: 1.3.6
  terraformWorkDir: ./examples/complete
  terraformS3Key: ${{ github.repository}}/${{ github.ref_name}}
  terraformModulesGithubOrg: ${{ github.repository_owner}}
  terraformBucket: terraform-module-state-files
  terraformDynamo: terraform-module-state-files

  awsRegion: us-east-1
  githubToken: ${{ secrets.CLOUD_TECH_GITHUB_TOKEN }}
  awsIamRoleSessionDuration: 7200


jobs:
  lint:
	name: Lint
	runs-on: ubuntu-20.04

  steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  - name: Checkout Github actions
    uses: actions/checkout@v4

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v2
    with:
      terraform_version: ${{ env.terraformVersion }}
      terraform_wrapper: false
  
  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v2
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-2 # Change to your preferred region

  - name: Terraform Initialize
    id: init
    run: |
      cd ${{ env.terraformWorkDir }}
      terraform init -backend-config="bucket=${{ env.terraformBucket }}" -backend-config="dynamodb_table=${{ env.terraformDynamo }}" -backend-config="key=${{ env.terraformS3Key}}" -backend-config="region=${{ env.awsRegion }}"

  - name: Terraform Format
    run: terraform fmt --check

  - name: Terraform Validate
    run: |
      cd ${{ env.terraformWorkDir }}
      terraform validate